# Generated by Django 5.0.6 on 2024-08-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agaclar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agac",
            name="sira",
            field=models.IntegerField(default=0),
        ),
    ]
