# Generated by Django 5.0.6 on 2024-08-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agaclar", "0002_agac_sira"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agac",
            name="sira",
        ),
        migrations.AddField(
            model_name="agac",
            name="img_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
