# Generated by Django 5.0.6 on 2024-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agaclar", "0003_remove_agac_sira_agac_img_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="agac",
            name="optik",
            field=models.ImageField(blank=True, null=True, upload_to="optik/"),
        ),
        migrations.AddField(
            model_name="agac",
            name="termal",
            field=models.ImageField(blank=True, null=True, upload_to="termal/"),
        ),
    ]
